# ===================================================================
# Spring Boot configuration.
# ===================================================================

server:
  port: 8888
#172.18.233.127（rm-wz90m0285094fd8d8.mysql.rds.aliyuncs.com）
spring:
  datasource:
    url: jdbc:mysql://172.18.233.127:3306/cloudplatform?useUnicode=true&amp;characterEncoding=utf8&amp;zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: clouyun
    password: clou$yun#@2016
    hikari:
      data-source-properties:  
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        usemicroServerPrepStmts: true
#线上内存库地址172.18.233.128（100.99.155.193）
  redis:
    host: 172.18.233.128
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 200
      max-wait: -1
    password: CLouyUn2016
  #数据召测配置
#线上前置机地址172.18.233.120(10.46.133.23)
randomcall:
  trmqueryperiod: 40
  mastercmdwaitfor: 10
  termicmdwaitfor: 40
  feps: =>172.18.233.120:10000