# ===================================================================
# Spring Boot configuration.
# ===================================================================

server:
  port: 8888
spring:
  datasource: 
    url: jdbc:mysql://10.13.10.243:3306/cloudplatform?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: nyznh
    password: szCLOU123
    hikari:
      data-source-properties:  
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        usemicroServerPrepStmts: true
  redis:
    host: 10.98.94.219
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  
