# ===================================================================
# Spring Boot configuration.
# ===================================================================

server:
  port: 8888
spring:
  datasource: 
    url: jdbc:mysql://10.13.10.243:3306/cloudplatform_yx?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: nyznh
    password: szCLOU123
    hikari:
      data-source-properties:  
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        usemicroServerPrepStmts: true
  redis:
    host: 10.13.3.19
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 200
      max-wait: -1
    password: CLouyUn2016
#数据召测配置
randomcall: 
    trmqueryperiod: 40
    mastercmdwaitfor: 10
    termicmdwaitfor: 40
    feps: =>10.13.3.27:10000
